% test of CodeBreakResults class

% load packet data
load('28388.mat', 'packets6');

% How many packet combinations in the experiment?
numCombinations = 10;
minimumPacketLength = 50;
numPacketsPerCombination = 2;
% Create a CodeBreakResult to keep track of experiment results
experimentResults = CodeBreakResults( ...
                                      numCombinations, ...
                                      numPacketsPerCombination, ...
                                      "checksum" ...
                                    );

for iExp = 1 : numCombinations
  [source, sourceName] = pickPackets( ...
                                      packets6, ...
                                      minimumPacketLength, ...
                                      numPacketsPerCombination ...
                                    );
  shortestSourceLength = min(strlength(source));
  combo  = PacketCombination( ...
                              2, 4, ...
                              sourceName, ...
                              shortestSourceLength, ...
                              source{1}, ...
                              source{2} ...
                            );
  combo.Combine();
  combo.Separate();
  combo.FindScalingFactors(@findScalingFactorByChecksum);
  combo.ComputeCodeBreakingResults(@immse);
  % Record the result of this experiment.
  experimentResults.SaveResult(combo);
end % experiments loop

% Record all results to an Excel file.
experimentResults.SaveToFile();
