function tableOut = createTable(ppCombo, numCombinations)
% Creates an empty table with cols = ppComb^2 + 1 and rows = numCombinations.
% Each row represents the results of a code breaking experiment.
  tempNames = {'packet'};
  iTemp = 2;
  for iIca = 1 : ppCombo
    for iSrc = 1 : ppCombo
      tempNames{iTemp} = strcat( ...
                                  'src', ...
                                  char(string(iSrc)), ...
                                  'est', ...
                                  char(string(iIca))...
                                );
      iTemp = iTemp + 1;
    end
  end
  for iIca = 1 : ppCombo
    tempNames{iTemp} = strcat('ipv4_', char(string(iIca)));
    iTemp = iTemp + 1;
  end
  varTypes = {'string'};
  for iVar = 2 : iTemp - 1
    varTypes{iVar} = 'double';
  end
  tableOut = table( ...
                  'Size', ...
                  [numCombinations size(tempNames, 2)], ...
                  'VariableTypes', ...
                  varTypes...
                );
  tableOut.Properties.VariableNames = tempNames;
end % createTable function
